# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

import gzip
import json
import os

METADATA_HEADER = """
#pragma once

#include "common.h"

// DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated from metadata.json.

// Compressed metadata for the web configurator
static const uint8_t metadata_compressed[] = {{
  {}
}};
"""

Import("env")

keyboard = env["PIOENV"]

metadata_path = os.path.join("keyboards", keyboard, "metadata.json")
if not os.path.exists(metadata_path):
    env.Exit(f"Metadata file not found: {metadata_path}")
with open(metadata_path, "r") as f:
    metadata = json.load(f)

uncompressed = json.dumps(metadata).encode("utf-8")
compressed = gzip.compress(uncompressed)

print(f"Uncompressed metadata size: {len(uncompressed)} bytes")
print(f"Compressed metadata size: {len(compressed)} bytes")

with open(os.path.join("include", "metadata.h"), "w") as f:
    f.write(METADATA_HEADER.format(", ".join(f"0x{byte:02X}" for byte in compressed)))
